on: [push, pull_request]
jobs:
  build:
    if: ${{github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)}}
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, Win32]
        include:
          - arch: x64
            triplet: x64-windows-static
          - arch: Win32
            triplet: x86-windows-static

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cmake -B build-${{matrix.arch}} -A ${{matrix.arch}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON -DVCPKG_TARGET_TRIPLET=${{matrix.triplet}} -DSAFETYHOOK_BUILD_TESTS=On
          cmake --build build-${{matrix.arch}} --config Release --parallel
          cmake --install build-${{matrix.arch}} --prefix ./install-${{matrix.arch}} --config Release
          
      - name: Test
        run: |
          ./install-${{matrix.arch}}/bin/test0.exe
          ./install-${{matrix.arch}}/bin/test1.exe
          ./install-${{matrix.arch}}/bin/test2.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.repository.name}}-${{matrix.arch}}
          path: install-${{matrix.arch}}/bin/*
